#!/usr/bin/env python3
"""生成 M6 的测试资源：UV 球体、立方体（OBJ）与棋盘格纹理（TGA）。

为什么自己生成资源？
    本机没有网络，拿不到 glTF 示例资产，也拿不到 cgltf / stb_image 这类库。
    为了让「外部 Mesh + 外部纹理」这条链路真实可复现，这里用一个脚本把资源
    生成到 assets/ 目录：脚本和生成物一起入库，任何人 clone 后都能得到同样的资源。

为什么用 OBJ + TGA？
    OBJ 是纯文本、带 v/vt/vn/f，解析器可以写得很小；
    TGA 未压缩格式的头部只有 18 字节，读写都不需要 zlib。
    这两者能让精力集中在渲染路径（Mesh / Material / SRV / Sampler / 纹理采样）上，
    而不是文件格式解析上 —— 这符合 M6 的目标。

用法：
    python tools/gen_assets.py
"""

import math
import os
import struct

ASSETS_DIR = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets")
)


# ---------------------------------------------------------------------------
# OBJ 写出
# ---------------------------------------------------------------------------
def write_obj(path, positions, uvs, normals, faces, comment):
    """写出一个最小 OBJ 文件。

    索引：positions / uvs / normals 三者一一对应，因此面直接用同一个下标。
    OBJ 的下标是 1-based。

    uv 约定：这里 v 的 0 在球体北极（顶部）。D3D 纹理坐标 v=0 在纹理顶部，
    因此生成物与 D3D 采样约定一致（不额外翻转）。
    """
    lines = ["# %s" % comment, "# generated by tools/gen_assets.py", ""]
    for p in positions:
        lines.append("v %.6f %.6f %.6f" % p)
    lines.append("")
    for t in uvs:
        lines.append("vt %.6f %.6f" % t)
    lines.append("")
    for n in normals:
        lines.append("vn %.6f %.6f %.6f" % n)
    lines.append("")
    for f in faces:
        a, b, c = f[0] + 1, f[1] + 1, f[2] + 1
        lines.append("f %d/%d/%d %d/%d/%d %d/%d/%d" % (a, a, a, b, b, b, c, c, c))
    lines.append("")

    with open(path, "w", encoding="ascii", newline="\n") as fp:
        fp.write("\n".join(lines))
    print("  wrote %s (%d verts, %d tris)" % (path, len(positions), len(faces)))


# ---------------------------------------------------------------------------
# 球体
# ---------------------------------------------------------------------------
def gen_sphere(radius=0.65, rings=24, sectors=32):
    """UV 球体：rings 为纬度分段（从北极到南极），sectors 为经度分段。"""
    positions, uvs, normals = [], [], []
    for i in range(rings + 1):
        theta = math.pi * i / rings          # 0 = 北极(+Y)，pi = 南极(-Y)
        sin_t, cos_t = math.sin(theta), math.cos(theta)
        for j in range(sectors + 1):
            phi = 2.0 * math.pi * j / sectors
            nx = sin_t * math.cos(phi)
            ny = cos_t
            nz = sin_t * math.sin(phi)
            positions.append((nx * radius, ny * radius, nz * radius))
            normals.append((nx, ny, nz))
            # v=0 在北极：与 D3D 纹理“v 向下”的约定一致
            uvs.append((j / sectors, i / rings))

    faces = []
    stride = sectors + 1
    for i in range(rings):
        for j in range(sectors):
            a = i * stride + j
            b = a + stride
            # 四边形 a, b, b+1, a+1 拆成两个三角形
            faces.append((a, b, b + 1))
            faces.append((a, b + 1, a + 1))
    return positions, uvs, normals, faces


# ---------------------------------------------------------------------------
# 立方体
# ---------------------------------------------------------------------------
def gen_cube(half=0.7):
    """带 UV 的立方体：每个面 4 个独立顶点（法线/UV 不共享）。"""
    # 每个面：(法线, 四个角, 该面的 uv 轴)
    faces_def = [
        ((0, 0, 1),  [(-1, -1, 1), (1, -1, 1), (1, 1, 1), (-1, 1, 1)]),      # +Z 前
        ((0, 0, -1), [(1, -1, -1), (-1, -1, -1), (-1, 1, -1), (1, 1, -1)]),  # -Z 后
        ((-1, 0, 0), [(-1, -1, -1), (-1, -1, 1), (-1, 1, 1), (-1, 1, -1)]),  # -X 左
        ((1, 0, 0),  [(1, -1, 1), (1, -1, -1), (1, 1, -1), (1, 1, 1)]),      # +X 右
        ((0, 1, 0),  [(-1, 1, 1), (1, 1, 1), (1, 1, -1), (-1, 1, -1)]),      # +Y 上
        ((0, -1, 0), [(-1, -1, -1), (1, -1, -1), (1, -1, 1), (-1, -1, 1)]),  # -Y 下
    ]
    face_uvs = [(0.0, 1.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0)]

    positions, uvs, normals, faces = [], [], [], []
    for normal, corners in faces_def:
        base = len(positions)
        for corner, uv in zip(corners, face_uvs):
            positions.append((corner[0] * half, corner[1] * half, corner[2] * half))
            normals.append(normal)
            uvs.append(uv)
        faces.append((base + 0, base + 1, base + 2))
        faces.append((base + 0, base + 2, base + 3))
    return positions, uvs, normals, faces


# ---------------------------------------------------------------------------
# TGA 纹理
# ---------------------------------------------------------------------------
def gen_checker_tga(path, size=256, cell=32):
    """生成一张棋盘格 TGA（32 位 BGRA，左上角为原点）。

    左上角画红块、右下角画绿块：这两个标记能一眼看出纹理的方向/翻转是否正确，
    是验证 UV 与采样器寻址模式的好帮手。
    """
    pixels = bytearray()
    for y in range(size):
        for x in range(size):
            if ((x // cell) + (y // cell)) % 2 == 0:
                r, g, b = 205, 205, 215          # 浅色格
            else:
                r, g, b = 55, 70, 115            # 深色格
            # 方向标记
            if x < cell and y < cell:
                r, g, b = 235, 60, 60            # 左上：红
            elif x >= size - cell and y >= size - cell:
                r, g, b = 60, 220, 90            # 右下：绿
            pixels += bytes((b, g, r, 255))      # TGA 是 BGRA

    header = struct.pack(
        "<BBBHHBHHHHBB",
        0,        # idLength
        0,        # colorMapType
        2,        # imageType = 2 未压缩真彩色
        0, 0, 0,  # colorMapSpecification（5 字节：firstEntry / length / entrySize）
        0, 0,     # xOrigin, yOrigin
        size,     # width
        size,     # height
        32,       # pixelDepth
        0x28,     # imageDescriptor: bit5=1 左上原点, 低 4 位=8 表示 8 位 alpha
    )
    with open(path, "wb") as fp:
        fp.write(header)
        fp.write(pixels)
    print("  wrote %s (%dx%d BGRA)" % (path, size, size))


def gen_uv_grid_tga(path, size=256, divisions=8):
    """生成一张 UV 参考纹理：底色随 u 渐变 + 网格线 + 边缘方向标记。

    用途是「让 UV 可见」：
      - 左边缘白色  -> u = 0
      - 顶部黄色条  -> v = 0（D3D 纹理的 v=0 在顶部）
      - 8x8 网格线  -> 可直接数出贴图重复与拉伸
    """
    pixels = bytearray()
    step = size // divisions
    for y in range(size):
        v = y / (size - 1)
        for x in range(size):
            u = x / (size - 1)
            r = int(235 * (1.0 - u) + 60 * u)
            g = int(90 + 80 * v)
            b = int(70 * (1.0 - u) + 245 * u)
            if (x % step) < 2 or (y % step) < 2:      # 网格线
                r, g, b = 18, 18, 24
            if y < 4:                                 # 顶部标记：v = 0
                r, g, b = 250, 220, 40
            if x < 4:                                 # 左边缘标记：u = 0
                r, g, b = 245, 245, 245
            pixels += bytes((b, g, r, 255))

    header = struct.pack("<BBBHHBHHHHBB", 0, 0, 2, 0, 0, 0, 0, 0, size, size, 32, 0x28)
    with open(path, "wb") as fp:
        fp.write(header)
        fp.write(pixels)
    print("  wrote %s (%dx%d BGRA)" % (path, size, size))


def main():
    os.makedirs(ASSETS_DIR, exist_ok=True)
    print("generating assets into %s" % ASSETS_DIR)

    p, t, n, f = gen_sphere()
    write_obj(os.path.join(ASSETS_DIR, "sphere.obj"), p, t, n, f, "UV sphere")

    p, t, n, f = gen_cube()
    write_obj(os.path.join(ASSETS_DIR, "cube.obj"), p, t, n, f, "textured cube")

    gen_checker_tga(os.path.join(ASSETS_DIR, "checker.tga"))
    gen_uv_grid_tga(os.path.join(ASSETS_DIR, "uv_grid.tga"))
    print("done.")


if __name__ == "__main__":
    main()
